stages:
  prepare:
    cmd: python3 main.py ${prepare} ${train} --prepare
    deps:
    - benchmark/data_module.py
    params:
    - prepare
    outs:
    - data
  train:
    cmd: python3 main.py ${prepare} ${train} --train
    deps:
    - benchmark/train_module.py
    - data
    params:
    - train
    outs:
    - output/models
  test:
    cmd: python3 main.py ${prepare} ${train} --test
    deps:
    - benchmark/test_module.py
    - output/models
    outs:
    - output/confusion
  evaluate:
    cmd: python3 main.py ${prepare} ${train} --evaluate
    deps:
    - benchmark/eval_module.py
    - output/confusion
    metrics:
    - output/metrics/metrics.json
