stages:
  prepare:
    cmd: python3 main.py ${prepare} ${train} --stage prepare
    deps:
    - benchmark/data_module.py
    params:
    - prepare
    outs:
    - data
  train:
    cmd: python3 main.py ${prepare} ${train} --stage train
    deps:
    - benchmark/train_module.py
    - data
    params:
    - train
    outs:
    - model
  test:
    cmd: python3 main.py ${prepare} ${train} --stage test
    deps:
    - benchmark/test_module.py
    - model
    outs:
    - output/confusion
  evaluate:
    cmd: python3 main.py ${prepare} ${train} --stage evaluate
    deps:
    - benchmark/eval_module.py
    - output/confusion
    metrics:
    - output/metrics/metrics.json
    plots:
    - output/metrics/confusion_matrix.png
  convert:
    cmd: python3 main.py ${prepare} ${train} ${convert} --stage convert
    deps:
    - benchmark/convert_module.py
    - model
    outs:
    - model.tflite
    - output/export/model.h
    - output/export/model.cpp
    - model_quant.tflite
    - output/export/model_quant.h
    - output/export/model_quant.cpp
  check:
    cmd: python3 main.py ${prepare} ${train} ${convert} ${check} --stage check
    deps:
    - benchmark/check_module.py
    - model.tflite
    metrics:
    - output/metrics/check.json