prepare:
  dataset: NASA-MSL
  batch_size: 512
  window_size: 100
  start_index_inputs_exported_in_c: 0
  n_inputs_exported_in_c: 0
train:
  model: GAN
  epochs: 10
  hidden_size: 128
  prediction_length: 1
  num_layers: 3
  learning_rate: 0.001
  export_model: model