prepare:
  dataset: NASA-MSL
  batch_size: 1024
  window_size: 100
  start_index_inputs_exported_in_c: 0
  n_inputs_exported_in_c: 0
train:
  model: LSTM
  epochs: 10
  hidden_size: 256
  num_layers: 2
  dropout: 0
  prediction_length: 1
  learning_rate: 0.001
convert:
  batch_size: 1
  entity: 0
check:
  batch_size: 1